[package]
name = "nanofilt"
version = "0.1.0"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
needletail = "0.4.0"
